server:
  port: 8080
  shutdown: graceful

spring:
  config:
    activate:
      on-profile: local, default
  datasource:
    url: jdbc:h2:mem:h2db;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS MONITOR
    driverClassName: org.h2.Driver
    username: protim
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

management:
  endpoint:
    health:
      show-details: always
  # Expose all actuator endpoints
  endpoints:
    web:
      exposure:
        include: "*"
